apiVersion: imageregistry.operator.openshift.io/v1
kind: Config
metadata:
  name: cluster
spec:
  defaultRoute: false
  managementState: Removed
  replicas: 2
  rolloutStrategy: RollingUpdate
  storage: {}
