---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: gitops-imageregistry-role
  annotations:
    argocd.argoproj.io/sync-wave: "0"
rules:
  - apiGroups:
      - imageregistry.operator.openshift.io
    resources:
      - configs
    verbs:
      - get
      - list
      - create
      - delete
      - update
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: gitops-imageregistry-rolebinding
  annotations:
    argocd.argoproj.io/sync-wave: "0"
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: gitops-imageregistry-role
subjects:
  - kind: ServiceAccount
    name: openshift-gitops-argocd-application-controller
    namespace: openshift-gitops
