apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: chrony-time-service
  namespace: openshift-gitops
spec:
  destination:
    name: ''
    namespace: ''
    server: 'https://kubernetes.default.svc'
  source:
    path: chrony-time-service/overlays/demo
    repoURL: 'https://github.com/cheevatee/ocp-gitops'
    targetRevision: main
  sources: []
  project: default
  syncPolicy:
    syncOptions:
      - Replace=true
      - PruneLast=true
      - ApplyOutOfSyncOnly=true
    automated:
      prune: true
      selfHeal: true
