apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
bases:
- ../../base
patches:
- eo-namespace.yaml
- eo-og.yaml
- olo-instance.yaml
- clf-instance.yaml
- target:
    kind: OperatorGroup
  patch: |- 
    - op: remove
      path: /metadata/labels/app.kubernetes.io~1instance
- target:
    kind: Namespace
  patch: |-
    - op: remove
      path: /metadata/labels/app.kubernetes.io~1instance
