apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../base
patches:
- eo-namespace.yaml
- olo-instance.yaml
- clf-instance.yaml
patches:
  - target:
      kind: Namespace
      name: openshift-operators-redhat
    patch: |- 
      - op: remove
        path: /metadata/labels/app.kubernetes.io~1instance
