apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: gitops-template-role
  annotations:
    argocd.argoproj.io/sync-wave: "0"
rules:
  - apiGroups:
      - template.openshift.io
    resources:
      - templates
    verbs:
      - get
      - list
      - create
      - delete
      - patch
      - update
      - watch
      - deletecollection
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: gitops-template-rolebinding
  annotations:
    argocd.argoproj.io/sync-wave: "0"
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: gitops-template-role
subjects:
  - kind: ServiceAccount
    name: openshift-gitops-argocd-application-controller
    namespace: openshift-gitops
