apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: loki-netobserv-lokistacks
  annotations:
    argocd.argoproj.io/sync-wave: "6"
rules:
- apiGroups:
  - 'loki.grafana.com'
  resources:
  - lokistacks
  verbs:
  - 'get'
  - 'create'
  - 'update'
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: loki-netobserv-lokistacks
  annotations:
    argocd.argoproj.io/sync-wave: "6"
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: loki-netobserv-lokistacks
subjects:
- kind: ServiceAccount
  name: openshift-gitops-argocd-application-controller
  namespace: openshift-gitops
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: loki-netobserv-flowcollectors
  annotations:
    argocd.argoproj.io/sync-wave: "6"
rules:
- apiGroups:
  - 'flows.netobserv.io'
  resources:
  - flowcollectors
  verbs:
  - 'delete'
  - 'deletecollection'
  - 'get'
  - 'list'
  - 'patch'
  - 'create'
  - 'update'
  - 'watch'
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: loki-netobserv-flowcollectors
  annotations:
    argocd.argoproj.io/sync-wave: "6"
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: loki-netobserv-flowcollectors
subjects:
- kind: ServiceAccount
  name: openshift-gitops-argocd-application-controller
  namespace: openshift-gitops
