apiVersion: v1
kind: ConfigMap
metadata:
  name: cluster-monitoring-config
  namespace: openshift-monitoring
  annotations:
    argocd.argoproj.io/sync-wave: "1"
data:
  config.yaml: |
    prometheusOperator: {}
    prometheusK8s:
      retention: 15d
      volumeClaimTemplate:
        metadata:
          name: gp3-csi-pvc
        spec:
          storageClassName: gp3-csi
          resources:
            requests:
              storage: 200Gi
    alertmanagerMain:
      volumeClaimTemplate:
        metadata:
          name: gp3-csi-pvc
        spec:
          storageClassName: gp3-csi
          resources:
            requests:
              storage: 10Gi
    kubeStateMetrics: {}
    grafana: {}
    telemeterClient: {}
    k8sPrometheusAdapter: {}
    openshiftStateMetrics: {}
    thanosQuerier: {}
