apiVersion: config.openshift.io/v1
kind: Project
metadata:
  creationTimestamp: null
  name: cluster
spec:
  projectRequestMessage: To provision Projects you must request access to cluster admin
  projectRequestTemplate:
    name: project-request
