apiVersion: config.openshift.io/v1
kind: Project
metadata:
  creationTimestamp: null
  name: cluster
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  projectRequestMessage: To provision Projects you must request access to cluster admin
  projectRequestTemplate:
    name: project-request
