---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: image-registry-storage
  annotations:
    argocd.argoproj.io/sync-wave: "3"
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 200Gi
