apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- gitops-machineconfig-rbac.yaml
- 99-master-chrony.yaml 
- 99-worker-chrony.yaml
- mcp-master-status.yaml
- mcp-worker-status.yaml
